config/routes.rb
Rails.application.routes.draw do
  get     "/posts"              => "posts#index",       as: :posts
  post    "/posts"              => "posts#create"
  get     "/posts/new"          => "posts#new",         as: :new_post
  get     "/posts/:name"        => "posts#show",        as: :post
  patch   "/posts/:name"        => "posts#update"
  delete  "/posts/:name"        => "posts#destroy"
  get     "/posts/:name/edit"   => "posts#edit",        as: :edit_post

  get     "/login"              => "sessions#new",      as: :login
  post    "/login"              => "sessions#create"

  delete  "/logout"             => "sessions#destroy",  as: :logout

  get     "/sign_up"            => "users#new",         as: :sign_up
  post    "/sign_up"            => "users#create"

end

app/models/post.rb
class Post < ActiveRecord::Base
  before_create :initialize_name

  def to_param
    name
  end

  def repository
    @repository ||= Repository.new(self)
  end

  def entries
    @entries ||= repository.head_entries
  end

  def entries=(entries)
    @entries = entries
  end

  def title
    if entry = entries.find { |e| e.path.present? }
      entry.path
    else
      "post:#{name}"
    end
  end

  private

    require "securerandom"

    def initialize_name
      self.name = SecureRandom.hex
    end
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  Invalid = Class.new(StandardError)

  attr_accessor :post, :description, :entries

  validates :entries, presence: true
  validate :entries_cant_be_empty

  class <<self
    def build_from_post(post)
      attributes = {
        post:         post,
        description:  post.description,
        entries:      post.entries,
      }

      new(attributes)
    end
  end

  def initialize(attributes = {})
    super(attributes)

    self.post ||= Post.new
    self.entries ||= new_record? ? [Entry.new] : []
  end

  def new_record?
    post.new_record?
  end

  def to_param
    post.to_param
  end

  def to_hash
    {
      description:  description,
      entries:      entries,
      new_record:   new_record?,
    }
  end

  def to_json
    to_hash.to_json
  end

  def entries_attributes=(attributes = {})
    self.entries = attributes.map do |(i, attrs)|
      Entry.new(attrs)
    end
  end

  concerning :Persistence do
    def update!(attributes = {})
      attributes.each do |attr, value|
        self.public_send("#{attr}=", value)
      end if attributes

      save!
    end

    def save!
      Post.transaction do
        validate!
        new_record? ? _create : _update
      end
    end

    private

      def _create
        save_post_record
        create_repository
        commit_entries
        true
      end

      def _update
        save_post_record
        commit_entries
        true
      end

      def save_post_record
        post.description = description
        post.save!
      end

      def create_repository
        post.repository.create!
      end

      def commit_entries
        post.repository.commit(entries)
      end
  end

  concerning :Validations do
    def validate!
      post.valid? && self.valid? || raise(Invalid)
    end

    private

      def entries_cant_be_empty
        if entries.any?(&:empty?)
          errors.add(:base, "Files can't be blank.")
        end
      end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post_form = PostForm.new
  end

  def edit
    @post_form = PostForm.build_from_post(@post)
  end

  def create
    @post_form = PostForm.new(post_params)
    @post_form.save!
    redirect_to @post_form.post, notice: 'Post was successfully created.'
  rescue PostForm::Invalid => e
    render :new
  end

  def update
    @post_form = PostForm.build_from_post(@post)
    @post_form.update!(post_params)
    redirect_to @post, notice: 'Post was successfully updated.'
  rescue PostForm::Invalid => e
    render :edit
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find_by!(name: params[:name])
    end

    def post_params
      params.require(:post_form).permit(
        :description,
        entries_attributes: [:path, :content]
      )
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
- if @post_form.errors.any?
  .panel.panel-danger
    .panel-heading
      h3.panel-title = "#{pluralize(@post_form.errors.count, "error")} prohibited this post from being saved:"
    .panel-body
      ul
        - @post_form.errors.full_messages.each do |message|
          li.text-danger = message

= react_component("PostForm", { post_form: @post_form.to_json }, { prerender: true })

app/views/posts/edit.html.slim
header.header.clearfix
  div.header-title.pull-left
    h1
      span.header-title-prefix.text-muted Editing
      '
      = link_to @post.title, @post
  div.header-menu.pull-right
    = link_to "Delete", post_path(@post), class: "btn btn-default btn-sm", method: :delete

= form_for @post_form, url: post_path(@post_form), method: "PATCH" do |f|
  == render 'form'

app/views/posts/index.html.slim
h1 All Posts

- @posts.each do |post|
  .post
    h3.post-title = link_to post.title, post
    - if post.description.present?
      p.post-description = post.description

app/views/posts/new.html.slim
header.header.clearfix
  div.header-title.pull-left
    h1
      span.header-title-prefix.text-muted Creating Post
  div.header-menu.pull-right

= form_for @post_form, url: posts_path do |f|
  == render 'form', locals: { f: f}

app/views/posts/show.html.slim
header.header.clearfix
  div.header-title.pull-left
    h1 = link_to @post.title, @post
  div.header-menu.pull-right
    = link_to "Edit", edit_post_path(@post), class: "btn btn-default btn-sm"
    '
    = link_to "Delete", post_path(@post), class: "btn btn-default btn-sm", method: :delete

.post
  - if @post.description.present?
    p.post-description.text-muted = @post.description

  .post-entries
    - @post.entries.each do |entry|
      .panel.panel-default
        .panel-heading = entry.path
        .panel-body
          pre.post-entry-content.syntax = highlight_entry_content(entry)