config/routes.rb
Rails.application.routes.draw do
  get     "/posts"              => "posts#index",       as: :posts
  post    "/posts"              => "posts#create"
  get     "/posts/new"          => "posts#new",         as: :new_post
  get     "/posts/:name"        => "posts#show",        as: :post
  patch   "/posts/:name"        => "posts#update"
  delete  "/posts/:name"        => "posts#destroy"
  get     "/posts/:name/edit"   => "posts#edit",        as: :edit_post

  get     "/login"              => "sessions#new",      as: :login
  post    "/login"              => "sessions#create"

  delete  "/logout"             => "sessions#destroy",  as: :logout

  get     "/sign_up"            => "users#new",         as: :sign_up
  post    "/sign_up"            => "users#create"

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Isaki
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-static-top role="navigation"
      .container
        .navbar-header
          = link_to "Isaki", posts_path, class: "navbar-brand"
        .collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            li = link_to new_post_path do
              span.glyphicon.glyphicon-plus
            - if signed_in?
              li = current_user.login
              li = link_to "Logout", logout_path, method: :delete
            - else
              li = link_to "Sign up", sign_up_path
              li = link_to "Login", login_path(original_url: request.url)
    .container
      .row
        .col-md-12
          - if flash[:notice].present?
            .alert.alert-info
              = flash[:notice]
          - if flash[:alert].present?
            .alert.alert-danger
              = flash[:alert]

          = yield